name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
      - staging
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ${{ github.ref_name == 'dev' && 'development/Dockerfile' || github.ref_name == 'staging' && 'staging/Dockerfile' || github.ref_name == 'main' && 'production/Dockerfile' }}
          tags: dockerhubusername/golang:${{ github.sha }}
          push: false  # Do not push the image to Docker Hub
      - name: Save Docker image to a file
        run: docker save -o image.tar dockerhubusername/golang:${{ github.sha }}
      - name: Upload Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: image.tar
          target: /home/${{ secrets.SERVER_USERNAME }}/
      - name: Load Docker image on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load -i /home/${{ secrets.SERVER_USERNAME }}/image.tar
      - name: Deploy to environment
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              COMPOSE_FILE=docker-compose.dev.yml
            elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
              COMPOSE_FILE=docker-compose.staging.yml
            elif [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
              COMPOSE_FILE=docker-compose.prod.yml
            fi
            docker-compose -f docker-compose.yml -f $COMPOSE_FILE up -d --build
